import Head from 'next/head'
import Image from 'next/image'
import Sidebar from '../Components/Sidebar'
import Song from '../Components/Song'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div class>
      <Head>
        <title>Spotify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-black'>
        <Sidebar />
        <Song />
      </main>
      <footer>
        {/* {} */}
      </footer>
    </div>
  )
}
